# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3825a5eed41cae59a65bd8c7f0a0fb0434d032e1a4737afbfcb485c628922122fbcca15a7df10597fc105c55d19c902d3eb392bbafa032a8030dfed8fd7b474a

test:
  secret_key_base: 1b7b76c62ddb0a1985be52da1640666a2e90091454aeb4557b1ed526cffb459c0862d1989af85088447cd0624d2f80540ea69fa67805fea2a45aa8894e24d6d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
